



export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOAD_PRODUCTS_BEGIN = 'LOAD_PRODUCTS_BEGIN'

export const SAVE_PRODUCT="SAVE_PRODUCT";
export const SAVE_PRODUCT_BEGIN="SAVE_PRODUCT_BEGIN";