

export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST"
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const LOAD_PRODUCTS_ERROR = "LOAD_PRODUCTS_ERROR"


export const LOAD_REVIEWS_REQUEST = "LOAD_REVIEWS_REQUEST"
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS"
export const LOAD_REVIEWS_ERROR = "LOAD_REVIEWS_ERROR"

export const SUBMIT_NEW_REVIEW_REQUEST = "SUBMIT_NEW_REVIEW_REQUEST"
export const SUBMIT_NEW_REVIEW_SUCCESS = "SUBMIT_NEW_REVIEW_SUCCESS"
export const SUBMIT_NEW_REVIEW_ERROR = "SUBMIT_NEW_REVIEW_ERROR"


export const BUY = "BUY"
